name: Deploy demo v0.6

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 (demo v0.6)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.V04_EC2_HOST }}
          username: ubuntu  
          key: ${{ secrets.V04_EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            
            PROJECT_ROOT="$HOME/optimal-loads-gfs-viewer"
            DEMO_DIR="$PROJECT_ROOT/2026-03-demo-v0.6"
            AIRFLOW_DATA="$HOME/airflow-data"
            ENV_FILE="$PROJECT_ROOT/2026-03-demo-v0.6/.env_06"


            # -------------------------------
            # Update code
            # -------------------------------
            cd "$PROJECT_ROOT"

            git fetch origin
            git checkout -B main origin/main  
            
            # ------------------------------
            # Deploy FastAPI
            # -------------------------------
            cd "$DEMO_DIR/fastapi-inventory"

            docker ps -q --filter "name=demo-v0-6-api" | grep -q . && docker stop demo-v0-6-api || true
            docker rm demo-v0-6-api || true

            docker build -t demo-v0-6-api .
            docker run -d \
              --name demo-v0-6-api \
              -p 80:8000 \
              --env-file "$ENV_FILE" \
              demo-v0-6-api